services:
  postgres:
    image: postgres:16
    volumes:
      - database:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: "postgres"
      POSTGRES_DB: medusa-v2
  redis:
    image: redis
    ports:
      - "6379:6379"
    volumes:
      - redis:/data

volumes:
  database:
  redis:
